### ISSUE TITLE
::selection looks strange

### ISSUE THREAD

**Issue by Bobbbay** [bedrocklinux/bedrocklinux-website#40]
This is selection:
![image](https://user-images.githubusercontent.com/49123594/89684521-a0bcad80-d8c8-11ea-9f7b-94dcef920225.png)

I would recommend having the background change to white and the color change to black on selection, like so:
```css
::selection {
    color: black;
    background-color: rgba(255,255,255,0.99);
}
```
Tweakable, of course. Cheers!
